<?php

defined('ABSPATH') or die();

add_filter( 'gform_pre_render_2', 'populate_posts' );
add_filter( 'gform_pre_validation_2', 'populate_posts' );
add_filter( 'gform_pre_submission_filter_2', 'populate_posts' );
add_filter( 'gform_admin_pre_render_2', 'populate_posts' );
function populate_posts( $form ) {
    foreach ( $form['fields'] as $field ) {
        if ( $field->type != 'select' || strpos( $field->cssClass, 'custom-choices' ) === false ) {
            continue;
        }

        $choices = nv_get_gf_choices();
        $possible_choices = [];

        foreach ( $choices as $choice ) {
            $possible_choices[] = array( 'text' => $choice, 'value' => sanitize_title($choice) );
        }

        $field->placeholder = '- Nicht festgelegt/ausgewählt -';
        $field->choices = $possible_choices;
    }

    return $form;
}

function nv_get_gf_choices()
{
     return [
        "Altmark",
        "Altötting",
        "Amberg-Sulzbach",
        "Anhalt-Bitterfeld",
        "Annaberg-Erzgebirge",
        "Ansbach",
        "Arnsberg",
        "Aschaffenburg",
        "Augsburg",
        "Bad Kissingen",
        "Bad Kreuznach",
        "Bamberg",
        "Bautzen",
        "Bayreuth",
        "Berchtesgadener Land - Rupertiwinkel",
        "Berlin",
        "Biberach a.d. Riß",
        "Böblingen",
        "Bodensee-Oberschwaben",
        "Bonn/Rhein-Sieg",
        "Börde",
        "Brandenburg an der Havel",
        "Braunschweig",
        "Bremen",
        "Bremerhaven",
        "Burgenlandkreis",
        "Cham",
        "Chemnitz",
        "Coburg",
        "Cottbus",
        "Cuxhaven",
        "Dachau",
        "Darmstadt-Südhessen",
        "Deggendorf",
        "Dessau",
        "Dingolfing-Landau",
        "Dithmarschen",
        "Donau-Ries",
        "Dortmund Kreis Unna Hamm",
        "Dresden",
        "Duisburg",
        "Düsseldorf",
        "Erding-Ebersberg",
        "Eichsfeldkreis",
        "Eichstätt",
        "Eisenach-Wartburgregion",
        "Emsland-Grafschaft Bentheim",
        "Erlangen",
        "Essen",
        "Esslingen",
        "Fichtelgebirge",
        "Flensburg",
        "Forchheim",
        "Frankfurt am Main",
        "Freiberg",
        "Freiburg",
        "Freising",
        "Freyung-Grafenau",
        "Fulda",
        "Fürth",
        "Garmisch-Partenkirchen",
        "Gera",
        "Gießen-Vogelsberg",
        "Gifhorn-Wolfsburg",
        "Glauchau",
        "Göppingen",
        "Görlitz",
        "Göttingen",
        "Günzburg",
        "Gunzenhausen",
        "Hagen / Ennepe-Ruhr",
        "Halle / Saale",
        "Hamburg",
        "Hameln",
        "Hanau-Gelnhausen-Schlüchtern",
        "Hannover",
        "Harz",
        "Harzkreis",
        "Haßberge",
        "Havelland",
        "Heidekreis Celle",
        "Heidelberg",
        "Heilbronn-Franken",
        "Hersfeld-Rotenburg",
        "Hildesheim",
        "Hochrhein",
        "Hof",
        "Holzminden",
        "Idar-Oberstein",
        "Ingolstadt",
        "Iserlohn",
        "Jerichower Land",
        "Kaiserslautern",
        "Kassel",
        "Kaufbeuren-Ostallgäu",
        "Kelheim",
        "Kempten / Oberallgäu",
        "Kiel",
        "Kleve",
        "Köln",
        "Konstanz-Hegau",
        "Krefeld",
        "Kronach",
        "Kulmbach",
        "Lahn-Dill",
        "Landsberg-Ammersee",
        "Landshut",
        "Leipzig",
        "Leverkusen / Rhein-Berg",
        "Lichtenfels",
        "Limburg-Weilburg-Diez",
        "Lindau / Westallgäu",
        "Lippe e.V.",
        "Lübeck",
        "Lüdenscheid",
        "Ludwigsburg",
        "Lüneburg - Elbe-Heide-Region",
        "Magdeburg",
        "Main-Spessart",
        "Mainz (Rheinhessen)",
        "Mannheim-Ludwigshafen",
        "Mansfeld-Südharz",
        "Marburg",
        "Memmingen / Unterallgäu",
        "Mittel-Lenne",
        "Mittelrhein",
        "Mittelthüringen",
        "Mittleres Ruhrgebiet",
        "Mönchengladbach",
        "Mühldorf",
        "München",
        "MY-Eifel",
        "Neubrandenburg",
        "Neuburg-Donau",
        "Neumarkt",
        "Neumünster",
        "Niederberg",
        "Nienburg / Weser",
        "Noabers",
        "Nordoberpfalz",
        "Nord Westfalen",
        "Nordfriesland",
        "Nordschwarzwald",
        "Nordthüringen",
        "Nürnberg",
        "Oberberg",
        "Oberhavel",
        "Offenbach am Main",
        "Oldenburg",
        "Ortenau",
        "Osnabrück",
        "Ostbrandenburg",
        "Ostfriesland / Papenburg",
        "Ostholstein",
        "Ostprignitz-Ruppin",
        "Ostwestfalen",
        "Ostwürttemberg",
        "Paderborn + Höxter",
        "Passau",
        "Plauen-Vogtland",
        "Potsdam",
        "Prignitz",
        "Regen",
        "Regensburg",
        "Remscheid",
        "Rems-Murr",
        "Rendsburg",
        "Reutlingen",
        "Rhein-Ahr",
        "Rhein-Hunsrück",
        "Rhein-Kreis Neuss",
        "Rhön-Grabfeld",
        "Rosenheim",
        "Rostock",
        "Rottal-Inn",
        "Saarbrücken",
        "Salzlandkreis",
        "Schaumburg",
        "Schleswig",
        "Schmalkalden-Meiningen",
        "Schwabach",
        "Schwandorf",
        "Schwarzwald-Baar-Heuberg",
        "Schweinfurt",
        "Schwerin",
        "Shanghai",
        "Segeberg",
        "Sieg-Westerwald",
        "Solingen",
        "Stade",
        "Stralsund",
        "Straubing",
        "Stuttgart",
        "Südpfalz",
        "Südwestfalen",
        "Südwestpfalz",
        "Teltow-Fläming",
        "Thüringer Wald",
        "Traunstein",
        "Trier",
        "Ulm",
        "Unterelbe",
        "Waldeck-Frankenberg",
        "Weißenburg",
        "Werra-Meißner",
        "Westerwald-Lahn",
        "Westthüringen",
        "Wetterau",
        "Wetzlar",
        "Wiesbaden",
        "Wittenberg",
        "Worms",
        "Wuppertal",
        "Würzburg",
        "Zwickau",
        "Zwischen Hunte und Weser"
    ];
}

add_filter( 'gform_submit_button', 'add_custom_css_classes', 10, 2 );
function add_custom_css_classes( $button, $form ) {
    $dom = new DOMDocument();
    $dom->loadHTML( '<?xml encoding="utf-8" ?>' . $button );
    $input = $dom->getElementsByTagName( 'input' )->item(0);
    $classes = $input->getAttribute( 'class' );
    $classes .= " mx-auto";
    $input->setAttribute( 'class', $classes );
    return $dom->saveHtml( $input );
}

add_action( 'admin_enqueue_scripts', 'nova_admin_styles' );
function nova_admin_styles() {
    wp_enqueue_style( 'admin_css_nova', get_template_directory_uri() . '/scss/vendor/guide-block-lines.css', false, '1.0.0' );
    wp_enqueue_style( 'admin_css_nova_2', get_template_directory_uri() . '/scss/admin/block-editor.css', false, '1.0.0' );
}  